### PR TITLE
fix: report jobs github actions

### PR DESCRIPTION
**Pull request by Sanix-Darker**
## WHY

This job was not working before due to parsing error while formating the output of the request

## HOW

The most obvious solution i made was to remove the explicit format output of the github action that has the role of formating the message to telegram !

### CODE REVIEW

**Review by RMPR — APPROVED** [review]
Probably needs some cleanup commits wise, otherwise it looks good.

**Comment by Sanix-Darker** [comment]
@RMPR let me know if everything looks coul for you now !

**Review by RMPR — COMMENTED** [review]
Minor: Can you elaborate in the commit message why this change?

**Review by RMPR — APPROVED** [review]

**Comment by Sanix-Darker** [comment]
Hey @RMPR any updates needed from this ?

**Pull request merged**
