### PR TITLE
fix: exclude archived repos

### PR DESCRIPTION
**Pull request by FanJups**
The list should not contain archived repos like the [former repo  osscameroon-blog](https://github.com/osscameroon/osscameroon-blog) .

After checking [GitHub API to list organization repositories](https://docs.github.com/en/rest/repos/repos#list-organization-repositories), we'll filter with the condition `archived==false` .

### CODE REVIEW

**Comment by Sanix-Darker** [comment]
Thanks for this PR !
Have you tested the jq filter filter with sample datas ?

`cat test.json | jq...`

**Comment by FanJups** [comment]
It works now

**Comment by FanJups** [comment]
Finally, I tested on Git Bash then I knew that I was wrong.

How to test ?

Copy the Example response in json format from [GitHub API List organization repositories](https://docs.github.com/en/rest/repos/repos#list-organization-repositories).

Paste the json response  into this command

`echo 'JSON_RESPONSE' | jq '.[] | select(.archived == false) | .url'`

Then, you're ready to go.

**Review by Sanix-Darker — APPROVED** [review]
Not tested, i will merge it and we're going to give it a try !

**Pull request merged**
